# Generated by Django 3.1.6 on 2021-02-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ubdated_by',
            new_name='updated_by',
        ),
    ]
